# Generated by Django 2.0 on 2019-07-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_remove_consultation_title'),
        ('patients', '0005_delete_patientfinancial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_form', models.NullBooleanField()),
                ('plots', models.IntegerField(default='0')),
                ('payday', models.DateField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_hour', models.TimeField(auto_now=True)),
                ('status', models.NullBooleanField()),
                ('consultation_id', models.ForeignKey(null=True, on_delete=models.SET(None), to='consultations.Consultation', verbose_name='Consulta')),
                ('patient_id', models.ForeignKey(null=True, on_delete=models.SET(None), to='patients.Patient', verbose_name='Paciente')),
            ],
        ),
    ]
