# Generated by Django 2.0 on 2019-07-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFinancial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_form', models.NullBooleanField()),
                ('plots', models.IntegerField(null=True)),
                ('payday', models.IntegerField(null=True)),
                ('status', models.NullBooleanField()),
            ],
        ),
    ]
