# Generated by Django 2.0 on 2019-07-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
