# Generated by Django 2.0 on 2019-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_delete_patientfinancial'),
        ('financier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfinancial',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='patients.Patient'),
        ),
    ]
