# Generated by Django 2.0 on 2019-07-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_consultation_title'),
        ('financier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfinancial',
            name='consultation_id',
        ),
        migrations.RemoveField(
            model_name='patientfinancial',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='patientfinancial',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.Consultation', verbose_name='Consulta'),
        ),
    ]
