# Generated by Django 2.0 on 2019-07-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0002_auto_20190710_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfinancial',
            name='outstanding_balance',
        ),
    ]
