# Generated by Django 2.0 on 2019-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0002_auto_20190717_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plots',
            name='type',
            field=models.IntegerField(default=2),
        ),
    ]
