# Generated by Django 2.0 on 2019-07-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0003_remove_patientfinancial_outstanding_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot01', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot02', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot03', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot04', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot05', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot06', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot07', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot08', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot09', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot10', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot11', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plot12', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date01', models.DateField(null=True)),
                ('date02', models.DateField(null=True)),
                ('date03', models.DateField(null=True)),
                ('date04', models.DateField(null=True)),
                ('date05', models.DateField(null=True)),
                ('date06', models.DateField(null=True)),
                ('date07', models.DateField(null=True)),
                ('date08', models.DateField(null=True)),
                ('date10', models.DateField(null=True)),
                ('date11', models.DateField(null=True)),
                ('date12', models.DateField(null=True)),
            ],
        ),
    ]
