# Generated by Django 2.0 on 2019-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0003_auto_20190717_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
