# Generated by Django 2.0 on 2019-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0003_patientfinancial_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfinancial',
            name='payday',
            field=models.DateField(null=True),
        ),
    ]
