# Generated by Django 2.0 on 2019-07-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0004_auto_20190719_1444'),
        ('financier', '0004_auto_20190718_1740'),
    ]

    operations = [
    ]
