# Generated by Django 2.0 on 2019-07-06 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0004_auto_20190706_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientfinancial',
            old_name='date',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='patientfinancial',
            old_name='hour',
            new_name='change_hour',
        ),
        migrations.AddField(
            model_name='patientfinancial',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
