# Generated by Django 2.0 on 2019-07-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0005_merge_20190719_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='status',
        ),
    ]
