# Generated by Django 2.0 on 2019-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0005_auto_20190706_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfinancial',
            name='change_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='consultations.Consultation', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='patients.Patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='payday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='plots',
            field=models.IntegerField(),
        ),
    ]
