# Generated by Django 2.0 on 2019-07-11 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0005_auto_20190711_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfinancial',
            name='payday',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
