# Generated by Django 2.2.4 on 2019-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0006_remove_cost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfinancial',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
