# Generated by Django 2.0 on 2019-07-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0006_auto_20190708_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfinancial',
            name='change_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='change_hour',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientfinancial',
            name='plots',
            field=models.IntegerField(default='0'),
        ),
    ]
