# Generated by Django 2.0 on 2019-07-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0007_auto_20190708_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientfinancial',
            old_name='consultation',
            new_name='consultation_id',
        ),
        migrations.RenameField(
            model_name='patientfinancial',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
