# Generated by Django 2.2.3 on 2019-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0009_auto_20190711_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
