# Generated by Django 2.2.3 on 2019-07-15 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0010_auto_20190711_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_form', models.NullBooleanField()),
                ('num_plots', models.IntegerField(null=True)),
                ('payday', models.IntegerField(null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_hour', models.TimeField(auto_now=True)),
                ('status', models.NullBooleanField()),
                ('plots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financier.Plots')),
            ],
        ),
    ]
