# Generated by Django 2.2.3 on 2019-07-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0011_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='cost_type',
            field=models.NullBooleanField(),
        ),
    ]
