# Generated by Django 2.2.3 on 2019-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0012_cost_cost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='date09',
            field=models.DateField(null=True),
        ),
    ]
