# Generated by Django 2.2.3 on 2019-07-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0013_plots_date09'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='payday',
            field=models.DateField(null=True),
        ),
    ]
