# Generated by Django 2.0 on 2019-07-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0014_auto_20190715_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plots',
            old_name='date01',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='plots',
            old_name='plot01',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='patientfinancial',
            name='plots',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date02',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date03',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date04',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date05',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date06',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date07',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date08',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date09',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date10',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date11',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='date12',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot02',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot03',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot04',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot05',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot06',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot07',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot08',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot09',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot10',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot11',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='plot12',
        ),
        migrations.AddField(
            model_name='plots',
            name='patient_financial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financier.PatientFinancial'),
        ),
    ]
