# Generated by Django 2.0 on 2019-07-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0015_auto_20190715_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plots',
            name='paid_day',
            field=models.DateField(null=True),
        ),
    ]
