# Generated by Django 2.0 on 2019-07-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financier', '0017_auto_20190717_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
