# Generated by Django 2.0 on 2019-06-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_remove_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('allDay', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.TextField()),
                ('backgroundColor', models.CharField(max_length=7)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.Patient')),
            ],
        ),
    ]
