# Generated by Django 2.0 on 2019-07-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('backgroundColor', models.CharField(default='#000000', max_length=7)),
                ('textColor', models.CharField(default='#ffffff', max_length=7)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start', models.DateField()),
                ('startTime', models.TimeField(null=True)),
                ('end', models.DateField()),
                ('endTime', models.TimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('holiday', models.BooleanField(default=False)),
                ('backgroundColor', models.CharField(default='#000000', max_length=7)),
                ('textColor', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.Procedure'),
        ),
    ]
