# Generated by Django 2.0 on 2019-07-07 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.Procedure'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
