# Generated by Django 2.0 on 2019-07-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_auto_20190629_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='endTime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='startTime',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='textColor',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='backgroundColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='start',
            field=models.DateField(),
        ),
    ]
