# Generated by Django 2.0 on 2019-07-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_auto_20190707_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='title',
        ),
    ]
