# Generated by Django 2.0 on 2019-07-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20190702_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
