# Generated by Django 2.0 on 2019-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_remove_consultation_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
    ]
