# Generated by Django 2.0 on 2019-07-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_auto_20190702_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='allDay',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='end',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='holiday',
        ),
    ]
