# Generated by Django 2.0 on 2019-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_auto_20190703_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('start', models.DateField()),
                ('startTime', models.TimeField(null=True)),
                ('end', models.DateField()),
                ('endTime', models.TimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('holiday', models.BooleanField(default=False)),
                ('backgroundColor', models.CharField(default='#000000', max_length=7)),
                ('textColor', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
    ]
