# Generated by Django 2.0 on 2019-07-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='start',
            new_name='date',
        ),
    ]
