# Generated by Django 2.0 on 2019-07-05 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_auto_20190703_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2019, 7, 5, 16, 58, 58, 340057)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2019, 7, 5, 16, 58, 58, 340057)),
        ),
    ]
