# Generated by Django 2.0 on 2019-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.TextField(default='Insira um Bairro'),
        ),
    ]
