# Generated by Django 2.0 on 2019-07-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientfinancial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientFinancial',
        ),
    ]
